server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh               # 路由的ID,没有固定规则 按要求唯一，建议配合服务名使用
          #          uri: http://localhost:8001      # 匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/get/**        # 断言，路径相匹配的进行路由

        - id: payment_routh2
          #          uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/lb/**
            - After=2020-08-12T10:25:00.668+08:00[Asia/Shanghai] # 表示必须满足在这个时间之后 这个格式的时间可用ZonedDateTime来生成
            # - Between=2020-08-10T10:25:00.668+08:00[Asia/Shanghai],2020-08-20T10:25:00.668+08:00[Asia/Shanghai] # 时间段内通过
            # - Cookie=username,chengming #请求必须带这个cookie:  "username=chengming"
            # - Header=X-Request-Id,\d+

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka